### ISSUE TITLE
1.12?

### ISSUE THREAD

**Issue by GriffinCodes** [14mRh4X0r/vanilla-irc#2]
As I'm sure you're aware, Minecraft is in version 1.12 now. Is there any chance this can be updated to run on a 1.12.1 server?

**Comment by 14mRh4X0r** [comment]
To be honest, I completely forgot about this project. It's also quite tedious to update, but maybe I'll look into automating it.

**Comment by GriffinCodes** [comment]
I browsed some of the update commits before opening this issue and they did seem very obscure (otherwise Id have attempted to update it myself). No worries if you don't want to update it, I completely understand. Thanks for looking into it through!
